---
language: python
services: docker

env:
  global:
    - ROLE_NAME: zend
  matrix:
    - TARGET_DISTRO: ubuntu1804
    - TARGET_DISTRO: ubuntu1604
    - TARGET_DISTRO: debian9

install:
  - pip install 'molecule[docker]'

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME aschult5.$ROLE_NAME
  - cd aschult5.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
