---
- name: pip docker
  pip: name=docker

- name: zcash-params volume info
  docker_volume_info:
    name: "{{ zend_zcash_srcvol }}"
    docker_host: "{{ zend_docker_host }}"
  register: zend_zcash_srcvol_info
  tags: prefetch

- name: zend docker container info
  docker_container_info:
    name: "{{ zend_docker_ctr_name }}"
    docker_host: "{{ zend_docker_host }}"
  register: zend_docker_ctr_info
  tags: prefetch

- name: zen-fetch-params before creating
  when:
    - not zend_zcash_srcvol_info.exists
    - not zend_docker_ctr_info.exists
  docker_container:
    name: zen-fetch-params
    docker_host: "{{ zend_docker_host }}"
    image: zencash/zen-node:{{ zend_ver }}
    state: started
    command: zen-fetch-params
    detach: no
    auto_remove: yes
    volumes:
    - "{{ [zend_zcash_srcvol, '/mnt/zcash-params'] | join(':') }}"
    env:
      LOCAL_USER_ID: "{{ zend_user_id }}"
      LOCAL_GRP_ID: "{{ zend_group_id }}"
  register: zen_fetch_params
  until: zen_fetch_params is success
  retries: 5
  delay: 10
  tags: prefetch

- name: zen docker network
  docker_network:
    name: "{{ zend_docker_net_name }}"
    docker_host: "{{ zend_docker_host }}"
    appends: yes
    ipam_config:
      - subnet: "{{ zend_docker_net_subnet }}"
        gateway: "{{ zend_docker_net_gateway }}"

- name: zend docker container
  docker_container:
    name: "{{ zend_docker_ctr_name }}"
    docker_host: "{{ zend_docker_host }}"
    image: "zencash/zen-node:{{ zend_ver }}"
    state: present
    restart_policy: unless-stopped
    log_driver: journald
    stop_timeout: "{{ zend_docker_ctr_stop_timeout }}"
    networks:
      - name: "{{ zend_docker_net_name }}"
        ipv4_address: "{{ zend_docker_ipv4 }}"
    purge_networks: yes
    tmpfs:
      - /tmp
      - /run
    volumes: "{{ [ zend_volume, zcash_volume, tls_volume if tls_volume|d('',true) else none ] | reject('none') | list }}"
    env:
        LOCAL_USER_ID: "{{ zend_user_id }}"
        LOCAL_GRP_ID: "{{ zend_group_id }}"
        RPC_ALLOWIP_PRESET: ANY
        RPC_ALLOWIP: "{{ zend_docker_ipv4|d('',true) }}"
        RPC_PORT: "{{ zend_port_rpc }}"
        EXTERNAL_IP: "{{ [zend_ipv4, zend_ipv6]|reject('undefined')|join(',')|d('', true) }}"
        PORT: "{{ zend_port_p2p }}"
        TLS_CERT_PATH: "{{ tls_cert_mnt | d('',true) }}"
        TLS_KEY_PATH: "{{ tls_key_mnt | d('',true) }}"
        OPTS: "-rpcworkqueue=512 -server=1 -listen=1 -txindex=1 -logtimestamps=1"
    published_ports:
      - "{{ zend_port_p2p }}:{{ zend_port_p2p }}"
  vars:
    zend_volume: "{{ [zend_dir, '/mnt/zen'] | join(':') }}"
    zcash_volume: "{{ [zend_zcash_srcvol, '/mnt/zcash-params'] | join(':') }}"
    tls_mntdir: /mnt/cert
    tls_srcdir: "{{ zend_tls_cert_abspath|dirname if zend_tls_cert_abspath|d('',true) else none }}"
    tls_volume: "{{ [tls_srcdir, tls_mntdir, 'ro'] | join(':') if tls_srcdir|d('',true) else none }}"
    tls_cert_mnt: "{{ [tls_mntdir, zend_tls_cert_abspath|basename] | join('/') if tls_volume|d('',true) else none }}"
    tls_key_mnt: "{{ [tls_mntdir, zend_tls_key_abspath|basename] | join('/') if tls_volume|d('',true) else none }}"
  notify: restart zend
