---
- name: pip docker
  pip:
    name: docker

- name: sudo group id
  getent:
    database: group
    key: sudo

- name: zen docker network
  docker_network:
    name: "{{ zend_docker_net_name }}"
    appends: yes
    ipam_config:
      - subnet: "{{ zend_docker_net_subnet }}"
        gateway: "{{ zend_docker_net_gateway }}"
  notify: docker network connect

- name: zend docker container
  docker_container:
    name: "{{ zend_docker_ctr_name }}"
    image: "zencash/zen-node:{{ zend_ver }}"
    state: present
    restart_policy: unless-stopped
    log_driver: journald
    stop_timeout: 600  # seconds
    tmpfs:
      - /tmp
      - /run
    volumes: "{{ [ zend_volume, zcash_volume, tls_volume if tls_volume|d('',true) else none ] | reject('none') | list }}"
    env:
        LOCAL_USER_ID: "{{ zend_user_id|d(omit,true) }}"
        LOCAL_GRP_ID: "{{ getent_group['sudo'][1]|d(omit,true) }}"
        RPC_ALLOWIP_PRESET: ANY
        RPC_ALLOWIP: "{{ zend_docker_ipv4|d(omit,true) }}"
        RPC_PORT: "{{ zend_port_rpc }}"
        EXTERNAL_IP: "{{ [zend_ipv4, zend_ipv6]|reject('undefined')|join(',')|d(omit, true) }}"
        PORT: "{{ zend_port_p2p }}"
        TLS_CERT_PATH: "{{ tls_cert_mnt | d(omit,true) }}"
        TLS_KEY_PATH: "{{ tls_key_mnt | d(omit,true) }}"
        OPTS: "-rpcworkqueue=512 -server=1 -listen=1 -txindex=1 -logtimestamps=1"
    published_ports:
      - "{{ zend_port_p2p }}:{{ zend_port_p2p }}"
  vars:
    zend_volume: "{{ [zend_dir, '/mnt/zen'] | join(':') }}"
    zcash_volume: zcash-params:/mnt/zcash-params
    tls_mntdir: /mnt/cert
    tls_srcdir: "{{ zend_tls_cert_path|dirname if zend_tls_cert_path|d('',true) and zend_tls_key_path|d('',true) else none }}"
    tls_volume: "{{ [tls_srcdir, tls_mntdir, 'ro'] | join(':') if tls_srcdir|d('',true) else none }}"
    tls_cert_mnt: "{{ [tls_mntdir, zend_tls_cert_path|basename] | join('/') if tls_volume|d('',true) else none }}"
    tls_key_mnt: "{{ [tls_mntdir, zend_tls_key_path|basename] | join('/') if tls_volume|d('',true) else none }}"
  notify: restart zend
