---
- import_tasks: swap.yaml
  when: swap_size is defined

# Packages
- name: apt update
  apt: update_cache=yes
- name: Install base packages
  apt:
    name: "{{ item }}"
  loop:
    - lsb-release
    - curl
    - tar

- import_tasks: network.yaml
  when: zennode_skip_network is not defined or zennode_skip_network == false
- import_tasks: zend-main.yaml
