---
- name: Create zend directory
  tags:
    - always
  file:
    path: "{{ zend_dir }}"
    state: directory
    owner: "{{ zend_user_name }}"
    mode: "u+rwx"

- name: Copy source wallet
  when: zend_wallet_src|d('', true)
  tags:
    - wallet
  copy:
    remote_src: "{{ zend_wallet_src_remote|d('no') }}"
    src: "{{ zend_wallet_src }}"
    dest: "{{ zend_dir }}/wallet.dat"
    owner: "{{ zend_user_name }}"
    mode: 0600
    backup: yes
  notify: restart zend

- import_tasks: blockchain.yml
  tags:
    - blockchain

- import_tasks: container.yml
  tags:
    - always

- import_tasks: service.yml
  tags:
    - service
