---
- name: Create/Get zend group
  group:
    name: "{{ zend_group_name }}"
    gid: "{{ zend_group_id | d(omit, true) }}"
    system: yes
  register: zend_group_info

- name: Create/Get zend user
  user:
    name: "{{ zend_user_name }}"
    uid: "{{ zend_user_id | d(omit, true) }}"
    groups:
      - "{{ zend_group_name }}"
    append: yes
    create_home: no
    system: yes
  register: zend_user_info

- name: Set zend user/group IDs
  set_fact:
    zend_group_id: "{{ zend_group_info.gid }}"
    zend_user_id: "{{ zend_user_info.uid }}"

- name: Create zend directory
  tags:
    - always
  file:
    path: "{{ zend_dir }}"
    state: directory
    owner: "{{ zend_user_name }}"
    mode: "u+rwx"

- name: Copy source wallet
  when: zend_wallet_src|d('', true)
  tags:
    - wallet
  copy:
    remote_src: "{{ zend_wallet_src_remote|d('no') }}"
    src: "{{ zend_wallet_src }}"
    dest: "{{ zend_dir }}/wallet.dat"
    owner: "{{ zend_user_name }}"
    mode: 0600
    backup: yes
  notify: restart zend

- import_tasks: blockchain.yml
  tags:
    - blockchain

- import_tasks: certificate.yml
  tags:
    - certificate

- import_tasks: container.yml
  tags:
    - always

- import_tasks: service.yml
  tags:
    - service
