---
- name: Install ufw
  apt: name=ufw

- name: ufw allow https/tcp
  ufw:
    rule: allow
    port: https
    proto: tcp

- name: ufw allow zend_port_p2p/tcp
  ufw:
    rule: allow
    port: "{{ zend_port_p2p }}"
    proto: tcp

- name: ufw enable
  ufw:
    state: enabled
    logging: "on"
