---
- name: Create zend service file
  copy:
    dest: "/lib/systemd/system/{{ zend_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash daemon

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      TimeoutStartSec=100
      ExecStart=/usr/bin/docker start {{ zend_docker_ctr_name }}
      ExecStop=/usr/bin/docker stop {{ zend_docker_ctr_name }}

      [Install]
      WantedBy=multi-user.target
  notify: systemd daemon-reload

- name: Enable zend service
  service:
    name: "{{ zend_svc_name }}.service"
    enabled: yes
