# gc_storage dependencies
- name: Install python3-pip
  apt: name=python3-pip
- name: Install boto
  pip: name=boto

- name: Download wallet
  gc_storage:
    bucket: "nodeler-219317.appspot.com"
    object: "/horizen/wallets/{{ inventory_hostname }}"
    dest: "{{ zennode_zen_dir }}/wallet.dat"
    mode: get
    gs_access_key: "{{ lookup('env', 'GS_ACCESS_KEY_ID') }}"
    gs_secret_key: "{{ lookup('env', 'GS_SECRET_ACCESS_KEY') }}"
- file:
    dest: "{{ zennode_zen_dir }}/wallet.dat"
    owner: "{{ zennode_user_name }}"
    mode: 0600