- name: Check required zen_dir variables
  assert:
    that:
      - zennode_user_name is defined
      - zennode_zen_conf is defined
      - zennode_zen_dir is defined
      - zennode_wallet_dir is defined
      - zennode_skip_blockchain is defined
      - zennode_ip is defined
    msg: Required variable missing.

# Zen directory setup
- name: Create zen directory
  file:
    path: "{{ zennode_zen_dir }}"
    state: directory
    owner: "{{ zennode_user_name }}"
- name: Create wallet directory
  file:
    path: "{{ zennode_wallet_dir }}"
    state: directory
    owner: "{{ zennode_user_name }}"

- name: Zen configuration file
  template:
    src: zen_conf.j2
    dest: "{{ zennode_zen_conf }}"
    owner: "{{ zennode_user_name }}"
    mode: 0644

- import_tasks: zen_chain.yml
  when: zennode_skip_blockchain == false

# gc_storage dependencies
- name: Install python3-pip
  apt: name=python3-pip
- name: Install boto
  pip: name=boto
- name: Download wallet
  gc_storage:
    bucket: "nodeler-219317.appspot.com"
    object: "/horizen/wallets/{{ inventory_hostname }}"
    dest: "{{ zennode_zen_dir }}/wallet.dat"
    mode: get
    gs_access_key: "{{ lookup('env', 'GS_ACCESS_KEY_ID') }}"
    gs_secret_key: "{{ lookup('env', 'GS_SECRET_ACCESS_KEY') }}"
- file:
    dest: "{{ zennode_zen_dir }}/wallet.dat"
    owner: "{{ zennode_user_name }}"
    mode: 0600

- name: Set zen directory owner
  file:
    path: "{{ zennode_zen_dir }}"
    state: directory
    owner: "{{ zennode_user_name }}"
    recurse: yes
