- name: Check required zen_chain_shard variables
  assert:
    that:
      - zen_dir is defined
      - zen_chain_shard is defined
      - gdrive_svc_acct is defined
    msg: Required variable missing.

- name: Download blockchain
  command: "gdrive download --service-account {{ gdrive_svc_acct }} {{ zen_chain_shard.id }}"
  args:
    chdir: /tmp
    creates: "/tmp/{{ zen_chain_shard.name }}"

- name: Extract blockchain
  unarchive:
    remote_src: yes
    src: "/tmp/{{ zen_chain_shard.name }}"
    dest: "{{ zen_dir }}"
    owner: "{{ user_name }}"

# Delete archive to save space
- name: Delete blockchain archive
  file:
    path: "/tmp/{{ zen_chain_shard.name }}"
    state: absent
