---
# Zen directory setup
- name: Create zen directory
  block:
    - file:
        path: "{{ zend_dir }}"
        state: link
        src: "{{ zend_dir_link }}"
        owner: "{{ zend_user_name }}"
  rescue:
    - file:
        path: "{{ zend_dir }}"
        state: directory
        owner: "{{ zend_user_name }}"

- name: Create wallet directory
  file:
    path: "{{ zend_dir }}/wallets"
    state: directory
    owner: "{{ zend_user_name }}"

- import_tasks: zend-chain.yml
  tags:
    - blockchain

- name: Set zen directory owner
  file:
    path: "{{ zend_dir }}"
    state: directory
    owner: "{{ zend_user_name }}"
    recurse: yes
