---
- name: Check required variables
  assert:
    that:
      - zennode_user_name is defined
      - zennode_zen_dir is defined
      - zennode_wallet_dir is defined
      - zennode_ipv4 is defined
    msg: Required variable missing.

# Zen directory setup
- name: Create zen directory
  block:
    - file:
        path: "{{ zennode_zen_dir }}"
        state: link
        src: "{{ zennode_zen_dir_link }}"
        owner: "{{ zennode_user_name }}"
  rescue:
    - file:
        path: "{{ zennode_zen_dir }}"
        state: directory
        owner: "{{ zennode_user_name }}"

- name: Create wallet directory
  file:
    path: "{{ zennode_wallet_dir }}"
    state: directory
    owner: "{{ zennode_user_name }}"

- import_tasks: zend-chain.yml
  tags:
    - blockchain

- name: Set zen directory owner
  file:
    path: "{{ zennode_zen_dir }}"
    state: directory
    owner: "{{ zennode_user_name }}"
    recurse: yes
