---
- name: Check for existing blocks
  stat:
    path: "{{ zend_dir }}/blocks"
  register: zend_chain_blocks
- name: Check for existing chainstate
  stat:
    path: "{{ zend_dir }}/chainstate"
  register: zend_chain_chainstate

- name: Bootstrap blockchain
  when: >
    zend_chain_seed_path|d()
    and not zend_chain_blocks.stat.exists
    and not zend_chain_chainstate.stat.exists
  block:
    - import_tasks: zend-chain-move.yml
  rescue:
    - import_tasks: zend-chain-copy.yml
  always:
    - name: Blockchain blocks directory
      file:
        path: "{{ zend_dir }}/blocks"
        state: directory
        recurse: true
        owner: "{{ zend_user_name }}"
        mode: "u+rw"
    - name: Blockchain chainstate directory
      file:
        path: "{{ zend_dir }}/chainstate"
        state: directory
        recurse: true
        owner: "{{ zend_user_name }}"
        mode: "u+rw"
