---
- name: Copy blockchain
  copy:
      remote_src: yes
      # Note src trailing slash indicates to copy directory's contents
      src: "{{ zen_chain_seed_path }}/"
      dest: "{{ zennode_zen_dir }}/"
      owner: "{{ zennode_user_name }}"
