- name: Check required zend_chain_shard variables
  assert:
    that:
      - zend_chain_shard is defined
      - gdrive_svc_acct is defined
    msg: Required variable missing.

- name: Download blockchain
  command: "gdrive download --service-account {{ gdrive_svc_acct }} {{ zend_chain_shard.id }}"
  args:
    chdir: /tmp
    creates: "/tmp/{{ zend_chain_shard.name }}"
  register: result
  until: result is success
  retries: 5
  delay: 10

- name: Extract blockchain
  unarchive:
    remote_src: yes
    src: "/tmp/{{ zend_chain_shard.name }}"
    dest: "{{ zend_dir }}"
    owner: "{{ zend_user_name }}"

# Delete archive to save space
- name: Delete blockchain archive
  file:
    path: "/tmp/{{ zend_chain_shard.name }}"
    state: absent
