---
- name: Check required zen_chain variables
  assert:
    that:
      - zennode_user_name is defined
      - zennode_zen_dir is defined
    msg: Required variable missing.

- name: Copy blockchain
  copy:
      remote_src: yes
      # Note src trailing slash indicates to copy directory's contents
      src: "{{ zen_chain_seed_path }}/"
      dest: "{{ zen_chain_dest_path }}/"

- name: Link blockchain blocks
  file:
    src: "{{ zen_chain_dest_path }}/blocks"
    dest: "{{ zennode_zen_dir }}/blocks"
    owner: "{{zennode_user_name }}"
    state: link

- name: Link blockchain chainstate
  file:
    src: "{{ zen_chain_dest_path }}/chainstate"
    dest: "{{ zennode_zen_dir }}/chainstate"
    owner: "{{zennode_user_name }}"
    state: link
