---
- name: sudo group id
  getent:
    database: group
    key: sudo

- name: zen docker network
  docker_network:
    name: "{{ zend_docker_net_name }}"
    ipam_config:
      - subnet: "{{ zend_docker_net_subnet }}"
        gateway: "{{ zend_docker_net_gateway }}"
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"

- name: zend docker container
  docker_container:
    name: zend
    image: "zencash/zen-node:{{ zend_ver|d('latest') }}"
    state: present
    restart_policy: unless-stopped
    log_driver: journald
    stop_timeout: 600  # seconds
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "{{ zend_dir }}:/mnt/zen"
      - zcash-params:/mnt/zcash-params
      - "{{ tls_volume|d(omit, true) }}"
    env:
        LOCAL_USER_ID: "{{ zend_user_id|d(omit,true) }}"
        LOCAL_GRP_ID: "{{ getent_group['sudo'][1]|d(omit,true) }}"
        RPC_ALLOWIP_PRESET: ANY
        RPC_ALLOWIP: "{{ zend_docker_ipv4|d(omit,true) }}"
        RPC_PORT: "8231"
        EXTERNAL_IP: "{{ [zend_ipv4, zend_ipv6]|reject('undefined')|join(',')|d(omit, true) }}"
        PORT: "9033"
        TLS_CERT_PATH: "{{ tls_cert_mnt | d(omit,true) }}"
        TLS_KEY_PATH: "{{ tls_key_mnt | d(omit,true) }}"
        OPTS: "-rpcworkqueue=512 -server=1 -listen=1 -txindex=1 -logtimestamps=1"
    networks:
      - name: "{{ zend_docker_net_name }}"
        ipv4_address: "{{ zend_docker_ipv4|d(omit,true) }}"
    published_ports:
      - 9033:9033
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
    tls_mntdir: /mnt/cert
    tls_srcdir: "{{ tls_cert_file|dirname if tls_cert_file|d('',true) and tls_key_file|d('',true) else none }}"
    tls_volume: "{{ [tls_srcdir, tls_mntdir, 'ro'] | join(':') if tls_srcdir|d('',true) else none }}"
    tls_cert_mnt: "{{ [tls_mntdir, tls_cert_file|basename] | join('/') if tls_volume else none }}"
    tls_key_mnt: "{{ [tls_mntdir, tls_key_file|basename] | join('/') if tls_volume else none }}"

- name: Create zend service file
  copy:
    dest: "/lib/systemd/system/{{ zend_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash daemon

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      TimeoutStartSec=100
      ExecStart=/usr/bin/docker start {{ zend_svc_name }}
      ExecStop=/usr/bin/docker stop {{ zend_svc_name }}

      [Install]
      WantedBy=multi-user.target
  notify:
    - systemd daemon-reload

- name: Enable zend service
  service:
    name: "{{ zend_svc_name }}.service"
    enabled: yes
