---
- name: Check required variables
  assert:
    that:
      - zennode_zen_dir is defined
      - container_net_name is defined
    msg: Required variable missing.

- name: zen docker network
  docker_network:
    name: "{{ container_net_name }}"
    ipam_config:
      - subnet: "{{ container_net_subnet }}"
        gateway: "{{ container_net_gateway }}"

- name: zend docker container
  docker_container:
    name: zend
    image: "zencash/zen-node:{{ zennode_zen_ver|default('latest') }}"
    state: present
    restart_policy: unless-stopped
    log_driver: journald
    stop_timeout: 600  # seconds
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "{{ zennode_zen_dir }}:/mnt/zen"
      - zcash-params:/mnt/zcash-params
    env:
        LOCAL_USER_ID: "{{ zennode_user_id|default(omit) }}"
        RPC_ALLOWIP: "{{ zennode_rpc_ipv4|default(omit) }}"
        EXTERNAL_IP: "{{ [zennode_ipv4, zennode_ipv6]|reject('undefined')|join(',')|default(omit) }}"
        TLS_KEY_PATH: "{{ secnode_tls_key|default(omit) }}"
        TLS_CERT_PATH: "{{ secnode_tls_cert|default(omit) }}"
    networks:
      - name: "{{ container_net_name }}"
        ipv4_address: "{{ zennode_rpc_ipv4|default(omit) }}"
    published_ports:
      - 9033:9033
