---
- name: Check for existing blocks
  stat:
    path: "{{ zend_dir }}/blocks"
  register: zend_chain_blocks
- name: Check for existing chainstate
  stat:
    path: "{{ zend_dir }}/chainstate"
  register: zend_chain_chainstate

- name: Bootstrap blockchain
  when: >
    zend_chain_seed_path|d()
    and not zend_chain_blocks.stat.exists
    and not zend_chain_chainstate.stat.exists
  block:
    # Try to move
    - assert:
        that: zend_chain_seed_move|d()
        msg: Won't attempt blockchain seed move

    - name: Move blockchain blocks
      command: mv {{ zen_chain_seed_path }}/blocks {{ zend_dir }}
      args:
        removes: "{{ zen_chain_seed_path }}/blocks"
        creates: "{{ zend_dir }}/blocks"
      register: mv_blocks

    - name: Move blockchain chainstate
      command: mv {{ zen_chain_seed_path }}/chainstate {{ zend_dir }}
      args:
        removes: "{{ zen_chain_seed_path }}/chainstate"
        creates: "{{ zend_dir }}/chainstate"
      register: mv_chainstate
  rescue:
    # Cleanup failed move
    - name: Replace blockchain blocks
      command: mv {{ zend_dir }}/blocks {{ zen_chain_seed_path }}
      args:
        removes: "{{ zend_dir }}/blocks"
        creates: "{{ zend_chain_seed_path }}/blocks"
      when: mv_blocks.changed|d()

    - name: Replace blockchain chainstate
      command: mv {{ zend_dir }}/chainstate {{ zen_chain_seed_path }}
      args:
        removes: "{{ zend_dir }}/chainstate"
        creates: "{{ zend_chain_seed_path }}/chainstate"
      when: mv_chainstate.changed|d()

    # Try to copy
    - name: Copy blockchain
      copy:
          remote_src: yes
          # Note src trailing slash indicates to copy directory's contents
          src: "{{ zend_chain_seed_path }}/"
          dest: "{{ zend_dir }}/"
          owner: "{{ zend_user_name }}"
  always:
    - name: Blockchain blocks directory
      file:
        path: "{{ zend_dir }}/blocks"
        state: directory
        recurse: true
        owner: "{{ zend_user_name }}"
        mode: "u+rw"
    - name: Blockchain chainstate directory
      file:
        path: "{{ zend_dir }}/chainstate"
        state: directory
        recurse: true
        owner: "{{ zend_user_name }}"
        mode: "u+rw"
