---
- import_tasks: zend-user.yml
  tags:
    - user

- name: Create zend directory
  file:
    path: "{{ zend_dir }}"
    state: directory
    owner: "{{ zend_user_name }}"
    mode: "u+rwx"

- name: Copy source wallet
  when: zend_wallet_src|d('', true)
  copy:
    remote_src: "{{ zend_wallet_src_remote|d('no') }}"
    src: "{{ zend_wallet_src }}"
    dest: "{{ zend_dir }}/wallet.dat"
    owner: "{{ zend_user_name }}"
    mode: 0600
    backup: yes
  tags:
    - wallet

- import_tasks: zend-chain.yml
  tags:
    - blockchain
- import_tasks: zend-install.yml
