---
# Zen directory setup
- name: Create zen directory
  file:
    path: "{{ zend_dir }}"
    state: directory
    owner: "{{ zend_user_name }}"

- name: Set zen directory owner
  file:
    path: "{{ zend_dir }}"
    state: directory
    owner: "{{ zend_user_name }}"
    recurse: yes
