---
- name: Check required variables
  assert:
    that:
      - zennode_zen_dir is defined
    msg: Required variable missing.

- name: zend docker container
  docker_container:
    name: zend
    image: "zencash/zen-node:{{ zennode_zen_ver|default('latest') }}"
    state: started
    restart_policy: always
    mounts:
      - name: zen-dir
        type: bind
        source: "{{ zennode_zen_dir }}"
        target: /mnt/zen
        read_only: no
      - name: zcash-params
        type: volume
        source: zcash-params
        target: /mnt/zcash-params
    env:
        LOCAL_USER_ID: "{{ zennode_user_id|default(omit) }}"
        RPC_ALLOWIP_PRESET: LOCALHOST
        EXTERNAL_IP: "{{ [zennode_ipv4, zennode_ipv6]|reject('undefined')|join(',')|default(omit) }}"
        TLS_KEY_PATH: "{{ zennode_tls_key|default(omit) }}"
        TLS_CERT_PATH: "{{ zennode_tls_cert|default(omit) }}"
    published_ports:
      - 9033:9033
