---
- name: Check required zen_chain variables
  assert:
    that:
      - zennode_user_name is defined
      - zennode_zen_dir is defined
    msg: Required variable missing.

- name: Copy blockchain
  copy:
      remote_src: yes
      # Note src trailing slash indicates to copy directory's contents
      src: "{{ zen_chain_seed_path }}/"
      dest: "{{ zennode_zen_dir }}/"
      owner: "{{ zennode_user_name }}"
