---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=1200
      when: ansible_os_family == 'Debian'

    - name: Install systemd-sysv
      apt: name=systemd-sysv
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_service_state: stopped
        docker_service_enabled: false
        docker_restart_handler_state: stopped

    - role: aschult5.zend
