---
- name: Converge
  hosts: all
  vars:
    docker_install_compose: false
    docker_service_state: stopped
    docker_service_enabled: false
    docker_restart_handler_state: stopped

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: zend
